
package yazlab1proje1;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
 static int kullanicialma; 
 int l=0;
    /**
     * Creates new form JFrame
     */
    public Login() {
        initComponents();
         
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPassword = new javax.swing.JToggleButton();
        userNameLogin = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JToggleButton();
        cretaeAccount = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 900));
        getContentPane().setLayout(null);

        newPassword.setBackground(new java.awt.Color(13, 82, 167));
        newPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newPassword.setForeground(new java.awt.Color(255, 255, 255));
        newPassword.setText("new password");
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(newPassword);
        newPassword.setBounds(670, 430, 140, 30);

        userNameLogin.setBackground(new java.awt.Color(255, 255, 255));
        userNameLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameLogin.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(userNameLogin);
        userNameLogin.setBounds(530, 160, 270, 60);

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(password);
        password.setBounds(530, 330, 270, 60);

        login.setBackground(new java.awt.Color(13, 82, 167));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(540, 580, 270, 50);

        cretaeAccount.setBackground(new java.awt.Color(13, 82, 167));
        cretaeAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cretaeAccount.setForeground(new java.awt.Color(255, 255, 255));
        cretaeAccount.setText("Create an account");
        cretaeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cretaeAccountActionPerformed(evt);
            }
        });
        getContentPane().add(cretaeAccount);
        cretaeAccount.setBounds(660, 740, 210, 50);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Change Password?");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 430, 160, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 130, 290, 110);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 300, 290, 110);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New to system?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 740, 180, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARGO DELIVERY SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 580, 410, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 130, 310, 310);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blue.png"))); // NOI18N
        jLabel5.setText("jLabel4");
        jLabel5.setMaximumSize(new java.awt.Dimension(450, 900));
        jLabel5.setMinimumSize(new java.awt.Dimension(450, 900));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 460, 900);

        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orange.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(450, 900));
        jLabel4.setMinimumSize(new java.awt.Dimension(450, 900));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, -10, 460, 920);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    String user_name;
    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
       newPassword password =new newPassword();
       password.setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_newPasswordActionPerformed

    private void cretaeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cretaeAccountActionPerformed
       this.setVisible(false);
       SignUp signUp=new SignUp();
       signUp.setVisible(true);
    }//GEN-LAST:event_cretaeAccountActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
        try {
        Connection myConn=(Connection) DriverManager.getConnection("jdbc:mysql://130.211.228.7:3306/transport","root","1234");
        Statement myStat1=(Statement)myConn.createStatement();
         ResultSet rs1;
                  rs1 = myStat1.executeQuery("SELECT id FROM users WHERE username="+"\""+userNameLogin.getText()+"\"");//sql sorgusu;
                  while(rs1.next())
                {
                    kullanicialma=rs1.getInt("id");
                }
    } catch (SQLException ex) {
        Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
    }
         
   
           
        if(userNameLogin.getText().length()==0 || password.getText().length()==0)
                  
       {
           JOptionPane.showMessageDialog(null, "Please fill the fields");
       }
       else
       {
                  try {
                      Connection myConn=(Connection) DriverManager.getConnection("jdbc:mysql://130.211.228.7:3306/transport","root","1234");
                      Statement myStat=(Statement)myConn.createStatement();
 
                      ResultSet rs=myStat.executeQuery("SELECT * FROM users");
                      ResultSet rs1;
                      System.out.println(kullanicialma);
                      while(rs.next())
                      {
                        
                          if(userNameLogin.getText().equals(rs.getString("username")) && password.getText().equals(rs.getString("password")))
                      {
                          user_name=userNameLogin.getText();
                           HomePage homePage=new HomePage(); 
                          homePage.setVisible(true);  
                           this.setVisible(false);
                         l++;
                      }
                      }
                      
                      if(l==0)
                      {
                          JOptionPane.showMessageDialog(null, "User not found");
                        
                      }
                        l=0;
                      
                          
                      
                          
            
        } catch (SQLException ex) {
                      System.out.println(ex);
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       }
       
      

    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton cretaeAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton login;
    private javax.swing.JToggleButton newPassword;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userNameLogin;
    // End of variables declaration//GEN-END:variables
}
