/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab1proje1;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static yazlab1proje1.Login.kullanicialma;

public class newPassword extends javax.swing.JFrame {

    /**
     * Creates new form newPassword
     */
    public newPassword() {
        initComponents();
               setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameNewpassword = new javax.swing.JTextField();
        passwordNewpassword = new javax.swing.JPasswordField();
        newpassword = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 300));
        setMinimumSize(new java.awt.Dimension(450, 410));
        getContentPane().setLayout(null);

        usernameNewpassword.setBackground(new java.awt.Color(255, 255, 255));
        usernameNewpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernameNewpassword.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(usernameNewpassword);
        usernameNewpassword.setBounds(130, 150, 190, 30);

        passwordNewpassword.setBackground(new java.awt.Color(255, 255, 255));
        passwordNewpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordNewpassword.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(passwordNewpassword);
        passwordNewpassword.setBounds(130, 230, 190, 30);

        newpassword.setBackground(new java.awt.Color(13, 82, 167));
        newpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newpassword.setForeground(new java.awt.Color(255, 255, 255));
        newpassword.setText("new password");
        newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(newpassword);
        newpassword.setBounds(120, 280, 210, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 120, 210, 70);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 200, 210, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("and change your password.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 80, 230, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter your user account's username ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 60, 290, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 82, 167), 5), "Change your Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 20, 320, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orange.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 400);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 530, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int usernameControl=0;
    private void newpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordActionPerformed
        LOOP:
         if( usernameNewpassword.getText().length()==0 ||passwordNewpassword.getText().length()==0 )
       {
           JOptionPane.showMessageDialog(null, "Please fill the fields ");
       }
         else{
       Connection connect=null;
        DbHelper db = new DbHelper();
        PreparedStatement statement = null;
         
             try {
            Connection myConn;     myConn = (Connection) DriverManager.getConnection("jdbc:mysql://130.211.228.7:3306/transport","root","1234");
                 Statement myStat=(Statement)myConn.createStatement();
                 ResultSet rs=myStat.executeQuery("SELECT * FROM users");
                      ResultSet rs1;
                      while(rs.next())
                      {
                        
                          if(usernameNewpassword.getText().equals(rs.getString("username")))
                      {
                         usernameControl++;
                        
                      }
                      }
             } catch (SQLException ex) {
                 Logger.getLogger(newPassword.class.getName()).log(Level.SEVERE, null, ex);
             }
                        
       
         if(usernameControl==1)   {       
        try {
            connect = db.getConnection();
            String sql = "UPDATE users  SET password=? WHERE username=?";
            statement = connect.prepareStatement(sql);
          
            statement.setString(1,passwordNewpassword.getText());
          statement.setString(2,usernameNewpassword.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Password update is successful");
        } catch (SQLException exception) {
            db.ShowError(exception);
        } finally {
       
            
        }
        Login menu=new Login();
     menu.setVisible(true);
     this.setVisible(false);
         }else{
             JOptionPane.showMessageDialog(null, "User not found!");
             usernameControl=0;
           
         }
         
         }
    }//GEN-LAST:event_newpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton newpassword;
    private javax.swing.JPasswordField passwordNewpassword;
    private javax.swing.JTextField usernameNewpassword;
    // End of variables declaration//GEN-END:variables
}
